[tool.astropy-bot]

[tool.astropy-bot.changelog_checker]
filename = "CHANGES.rst"


[build-system]
requires = ["setuptools", "setuptools_scm", "wheel", "cython==0.29.32", "oldest-supported-numpy", "extension-helpers"]
build-backend = 'setuptools.build_meta'
