name: Build wheels

on:
  workflow_dispatch:
  release:
    types:
      - published
  pull_request:
    branches:
      - master

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      # Used to host cibuildwheel
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.10.0

      - name: Build wheels
        # uses: pypa/cibuildwheel@d4a2945fcc8d13f20a1b99d461b8e844d5fc6e23  # v2.21.1
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install numpy>=2 Cython extension-helpers
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.11"
          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl